scanner:
    diff_only: True  # If False, the entire file touched by the Pull Request is scanned for errors. If True, only the diff is scanned.
    linter: pycodestyle  # Other option is flake8

no_blank_comment: False  # If True, no comment is made on PR without any errors.
descending_issues_order: True  # If True, PEP 8 issues in message will be displayed in descending order of line numbers in the file

pycodestyle:  # Same as scanner.linter value. Other option is flake8
    max-line-length: 112  # Default is 79 in PEP 8
