name: option-tests

on:
  workflow_dispatch:
  pull_request:
  push:
    branches: [ main ]


jobs:
  test_defaults:
    name: Test options defaults
    runs-on: ${{ matrix.os }}
    defaults:
      run:
        shell: bash
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-18.04, ubuntu-20.04]

    steps:
      # To use this repository's private action,
      # you must check out the repository
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: cccc action step (all sources, no options)
        uses: ./ # Uses an action in the root directory
        with:
          github_token: ${{secrets.GITHUB_TOKEN }}

      - name: upload report
        uses: actions/upload-artifact@v2
        with:
          name: metrics-defaults-${{ matrix.os }}
          path: ./metrics

  test_dirs:
    name: Test options directories
    runs-on: ${{ matrix.os }}
    defaults:
      run:
        shell: bash
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-18.04, ubuntu-20.04]

    steps:
      # To use this repository's private action,
      # you must check out the repository
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: cccc action step with directories
        uses: ./ # Uses an action in the root directory
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          target_branch: gh-pages
          source_dirs: |
            tests/java
            tests/cpp

      - name: upload report
        uses: actions/upload-artifact@v2
        with:
          name: metrics-dirs-${{ matrix.os }}
          path: ./metrics

  test_exts:
    name: Test options extensions
    runs-on: ${{ matrix.os }}
    defaults:
      run:
        shell: bash
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-18.04, ubuntu-20.04]

    steps:
      # To use this repository's private action,
      # you must check out the repository
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: cccc action step with file extensions
        uses: ./ # Uses an action in the root directory
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          target_branch: gh-pages
          source_dirs: |
            tests/java
            tests/cpp
            tests/c
          file_extensions: |
            .h
            .cpp

      - name: upload report
        uses: actions/upload-artifact@v2
        with:
          name: metrics-exts-${{ matrix.os }}
          path: ./metrics
